
/// 
/// everything related to genome
/// 
/// 
/// 


/// Genome trait
/// generated by  github copilot
pub trait Genome {
    fn new() -> Self;
    fn mutate(&mut self);
    fn crossover(&self, other: &Self) -> Self;
    //fn fitness(&self) -> f64;
    fn print(&self);
}